version: '3.1'
services:
  nginx:
    build:
      context: ../dockerfiles
      dockerfile: Nginx
    ports:
      - "80:80"
      - "433:433"
    restart: always
    tty: true
    container_name: nginx
    volumes:
      - ../www:/var/www/html:rw
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/vhost:/etc/nginx/vhost:ro
      - ../config/nginx/ssl:/etc/nginx/ssl:ro
      - ../config/nginx/rewrite:/etc/nginx/rewrite:ro
      - ../config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      #- ../config/nginx/enable-php.conf:/etc/nginx/enable-php.conf:ro
      #- ../config/nginx/enable-php-pathinfo.conf:/etc/nginx/enable-php-pathinfo.conf:ro
      - ../logs/nginx:/var/logs/nginx:rw
    networks:
     - lnmp-network
networks:
 lnmp-network:
