version: '3.1'
services:
  nginx:
    build:
      context: ../dockerfiles
      dockerfile: Nginx
    ports:
      - "80:80"
      - "433:433"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m" # 单个文件
        max-file: "10" # 最多几个文件
    container_name: nginx
    volumes:
      - ../www:/var/www/html:rw
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/vhost:/etc/nginx/vhost:ro
      - ../config/nginx/ssl:/etc/nginx/ssl:ro
      - ../config/nginx/rewrite:/etc/nginx/rewrite:ro
      - ../config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ../config/nginx/enable-php.conf:/etc/nginx/enable-php.conf:ro
      - ../config/nginx/enable-php-pathinfo.conf:/etc/nginx/enable-php-pathinfo.conf:ro
      - ../config/nginx/pathinfo.conf:/etc/nginx/pathinfo.conf:ro
      - ../logs/nginx:/var/logs/nginx:rw

  php:
    build:
      context: ../dockerfiles
      dockerfile: PHP
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m" # 单个文件
        max-file: "10" # 最多几个文件
    container_name: php
    volumes:
      - ../www:/var/www/html:rw
      - ../logs/php:/var/logs/php:rw
      - ../config/crontab:/etc/cron.d/cron:ro
      - ../config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ../config/supervisor:/etc/supervisor/conf.d:ro
      - ../logs/supervisor:/etc/supervisor/logs:rw

  mysql:
    build:
      context: ../dockerfiles
      dockerfile: Mysql
    ports:
      - "3306:3306"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m" # 单个文件
        max-file: "10" # 最多几个文件
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ../volumes/mysql:/var/lib/mysql:rw

  redis:
    build:
      context: ../dockerfiles
      dockerfile: Redis
    restart: always
    command: redis-server --requirepass 123456
    logging:
      driver: json-file
      options:
        max-size: "1m" # 单个文件
        max-file: "10" # 最多几个文件
    container_name: redis
    volumes:
      - ../volumes/redis:/data:rw
