version: '3.1'
services:
  memcached:
    build:
      context: ../dockerfiles
      dockerfile: Memcached
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    container_name: memcached
