version: '3.1'
services:
  memcached:
    build:
      context: ../dockerfiles
      dockerfile: Memcached
      args:
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
        MEMCACHED_EXPOSE: ${MEMCACHED_EXPOSE}
    restart: always
    environment:
      MAINTAINER: "$MAINTAINER"
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    container_name: memcached
