version: '3.1'
services:
  mongodb:
    build:
      context: ../dockerfiles
      dockerfile: Mongodb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    container_name: mongodb