version: '3.1'
services:
  rabbitmq:
    build:
      context: ../dockerfiles
      dockerfile: Rabbitmq
      args:
        RabbitMQ_VERSION: ${RabbitMQ_VERSION}
        RabbitMQ_EXPOSE: ${RabbitMQ_EXPOSE}
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    container_name: rabbitmq
    ports:
      - "${RabbitMQ_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "$RABBITMQ_DEFAULT_USER"
      RABBITMQ_DEFAULT_PASS: "$RABBITMQ_DEFAULT_PASS"
    volumes:
      - ../volumes/rabbitmq:/var/lib/rabbitmq:rw