version: '3.1'
services:
redis:
  build:
    context: ../dockerfiles
    dockerfile: Redis
  restart: always
  command: redis-server --requirepass 123456
  logging:
    driver: json-file
    options:
      max-size: "1m"
      max-file: "10"
  container_name: redis
  volumes:
    - ../volumes/redis:/data:rw